name: Build and Test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches-ignore:
      - "no-ci-*"

env:
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

jobs:
  checkSource:
    name: Check Source Code
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - uses: pre-commit/action@v3.0.1

  buildAndTest:
    name: >-
      Build & Test
      (${{ matrix.os }})
      (C++ ${{ matrix.cxx-standard }})
      ${{ startsWith(matrix.os, 'macos-') && (matrix.os == 'macos-14' && '(ARM64)' || '(AMD64)') || '' }}
    needs: checkSource
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-14
          - ubuntu-22.04
          - windows-2022
        cxx-standard:
          - 17

    steps:
      - name: Checkout Mapnik
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Install required system packages
        shell: bash
        run: |
          if [ "${RUNNER_OS}" == "Linux" ]; then
            sudo apt update
            sudo apt install -y \
              cmake \
              gperf \
              lcov \
              libxxf86vm-dev \
              ninja-build \
              pkgconf \
              postgresql-client \
              libboost-filesystem-dev \
              libboost-program-options-dev \
              libboost-regex-dev \
              libboost-system-dev \
              libboost-thread-dev \
              libcairo2-dev \
              libcurl4-openssl-dev \
              libfreetype-dev \
              libgdal-dev \
              libharfbuzz-dev \
              libicu-dev \
              libjpeg-dev \
              libpng-dev \
              libpq-dev \
              libproj-dev \
              libsqlite3-dev \
              libtiff-dev \
              libwebp-dev \
              libxml2-dev \
              libgl1-mesa-dev \
              qt6-base-dev \
              zlib1g-dev
          elif [ "${RUNNER_OS}" == "macOS" ]; then
            brew install \
              cmake \
              lcov \
              ninja \
              pkg-config \
              boost \
              cairo \
              freetype \
              gdal \
              harfbuzz \
              icu4c \
              jpeg-turbo \
              libpng \
              libpq \
              libtiff \
              libxml2 \
              postgresql \
              proj \
              qt \
              sqlite \
              webp
          elif [ "${RUNNER_OS}" == "Windows" ]; then
            choco install \
              ninja \
              OpenCppCoverage
            echo "C:\Program Files\OpenCppCoverage" >> ${GITHUB_PATH}
          fi

      - name: Enable Developer Command Prompt (Windows)
        uses: ilammy/msvc-dev-cmd@v1
        if: runner.os == 'Windows'

      - name: Set CMAKE_BUILD_PARALLEL_LEVEL, CTEST_PARALLEL_LEVEL & PRESET
        shell: bash
        run: |
          LC_RUNNER_OS=$(echo "${RUNNER_OS}" | perl -ne "print lc")
          PRESET=${LC_RUNNER_OS}-ci
          if [ "${RUNNER_OS}" == "Linux" ]; then
            echo "CMAKE_BUILD_PARALLEL_LEVEL=$(nproc)" >> ${GITHUB_ENV}
            echo "CTEST_PARALLEL_LEVEL=$(nproc)" >> ${GITHUB_ENV}
          elif [ "${RUNNER_OS}" == "macOS" ]; then
            echo "CMAKE_BUILD_PARALLEL_LEVEL=$(sysctl -n hw.logicalcpu)" >> ${GITHUB_ENV}
            echo "CTEST_PARALLEL_LEVEL=$(sysctl -n hw.logicalcpu)" >> ${GITHUB_ENV}
            PRESET=${LC_RUNNER_OS}-ci-${{ matrix.os == 'macos-14' && 'arm64' || 'x64' }}
          elif [ "${RUNNER_OS}" == "Windows" ]; then
            echo "CMAKE_BUILD_PARALLEL_LEVEL=$(pwsh -Command '(Get-CimInstance -ClassName Win32_ComputerSystem).NumberOfLogicalProcessors')" >> ${GITHUB_ENV}
            echo "CTEST_PARALLEL_LEVEL=$(pwsh -Command '(Get-CimInstance -ClassName Win32_ComputerSystem).NumberOfLogicalProcessors')" >> ${GITHUB_ENV}
          fi
          echo "PRESET=${PRESET}" >> ${GITHUB_ENV}

      - name: Set CPATH, ICU_ROOT & LIBRARY_PATH (macOS)
        shell: bash
        run: |
          echo "CPATH=$(brew --prefix)/include" >> ${GITHUB_ENV}
          echo "ICU_ROOT=$(brew --prefix icu4c)" >> ${GITHUB_ENV}
          echo "LIBRARY_PATH=$(brew --prefix)/lib" >> ${GITHUB_ENV}
        if: runner.os == 'macOS'

      - name: Link VCPKG_INSTALLATION_ROOT to vcpkg (Windows)
        shell: bash
        run: |
          ln -s ${VCPKG_INSTALLATION_ROOT} vcpkg
        if: runner.os == 'Windows'

      - name: Configure CMake
        shell: bash
        run: |
          cmake --preset ${PRESET} \
            -DBUILD_SHARED_LIBS:BOOL=ON \
            -DCMAKE_CXX_STANDARD:STRING=${{ matrix.cxx-standard }}  \
            -DUSE_MEMORY_MAPPED_FILE:BOOL=ON \
            -LA

      - name: Build
        shell: bash
        run: |
          cmake \
            --build \
            --preset ${PRESET}

      - name: Run Tests
        uses: ./.github/actions/run_tests
        with:
          cmake-preset: ${{ env.PRESET }}
