name: Release Linux

on:
  push:
    branches:
      - "*"
  pull_request:
    branches-ignore:
      - "no-ci-*"
env:
  PRESET: linux-ci-release

jobs:
  build:
    runs-on: "ubuntu-22.04"
    steps:

      - name: Checkout Mapnik
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install required system packages
        shell: bash
        run: |
            sudo apt update
            sudo apt install -y \
              ninja-build \
              libboost-filesystem-dev \
              libboost-program-options-dev \
              libboost-regex-dev \
              libcairo2-dev \
              libfreetype6-dev \
              libgdal-dev \
              libharfbuzz-dev \
              libicu-dev \
              libjpeg-dev \
              libproj-dev \
              libtiff-dev \
              libwebp-dev \
              libxml2-dev

      - name: Configure CMake
        run: |
          cmake --preset ${PRESET} \
             -LA

      - name: Build
        run: |
          cmake \
            --build \
            --preset ${PRESET}

      - name: Package
        run: |
          cmake \
            --build \
            --preset ${PRESET} \
            --target package

      - name: Upload mapnik debian package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PRESET }}-deb
          path: build/mapnik-*.deb
